spring:
  application:
    version: "1.0"
    formatted-version: "(v1.0)"
    name: "Lavalink"
  cloud:
    config:
      enabled: false

server:
  address: 0.0.0.0
  port: ${PORT:2333}

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"

    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"

  server:
    password: "Shivi@2006"

    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false

    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true

    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

plugins:
  youtube:
    enabled: true
    clients:
      plugins:
  youtube:
    enabled: true
    clients:
      - IOS
      - WEB
      

  lavasrc:
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
    
    providers:
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"
      - "scsearch:%QUERY%"

    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO